window_height = 621
window_width = 621
board_width = board_height = 601
piece_border = 2
row_num_width = 40
row_num_height = board_height
col_num_width = board_width
col_num_height = 40
valid_move_border = 28
line_number_font = "Consolas"
line_number_font_color = "white"
line_number_font_size = 20
scoreboard_piece_icon_size = 20
scoreboard_piece_icon_offset = 10
scoreboard_width = window_width
scoreboard_height = 40
scoreboard_score_width = 80
scoreboard_font = "Consolas"
scoreboard_font_color = "white"
scoreboard_font_size = 20
message_bar_width = window_width - (2 * scoreboard_score_width)
message_bar_height = 40
message_font = "Consolas"
message_font_color = "white"
message_font_size = 18